### ISSUE TITLE
Build failing after update to v2.0.0

### ISSUE THREAD

**Issue by johnsimons** [dagrejs/dagre#492]
Here is the output from the build:

```
vite build

vite v7.2.4 building client environment for production...
✓ 1267 modules transformed.
src/components/messages/FlowDiagram/useLayout.ts:1:19 - error TS7016: Could not find a declaration file for module '@dagrejs/dagre'. '/Users/xxxxx/Projects/xxxxxxx/src/Frontend/node_modules/@dagrejs/dagre/dist/dagre.esm.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/dagrejs__dagre` if it exists or add a new declaration (.d.ts) file containing `declare module '@dagrejs/dagre';`

1 import dagre from "@dagrejs/dagre";
```

**Comment by johnsimons** [comment]
I tried the master version and still failing.

I also tried changing the import to `import { graphlib, layout } from "@dagrejs/dagre";` and still no good.

The error:
```
src/components/messages/FlowDiagram/useLayout.ts:1:34 - error TS7016: Could not find a declaration file for module '@dagrejs/dagre'. 'xxxx/src/Frontend/node_modules/@dagrejs/dagre/dist/dagre.esm.js' implicitly has an 'any' type.
  There are types at '/xxxx/src/Frontend/node_modules/@dagrejs/dagre/dist/dagre.d.ts', but this result could not be resolved when respecting package.json "exports". The '@dagrejs/dagre' library may need to update its package.json or typings.

1 import { graphlib, layout } from "@dagrejs/dagre";
                                   ~
```

**Comment by johnsimons** [comment]
Just tried master again, and the only errors now are:
```
vite v7.2.4 building client environment for production...
✓ 1278 modules transformed.
src/components/messages/FlowDiagram/useLayout.ts:8:40 - error TS2339: Property 'Graph' does not exist on type 'typeof graphlib'.

8   const graph = ref(new dagre.graphlib.Graph());
                                         ~~~~~

src/components/messages/FlowDiagram/useLayout.ts:12:43 - error TS2339: Property 'Graph' does not exist on type 'typeof graphlib'.

12     const dagreGraph = new dagre.graphlib.Graph();
                                             ~~~~~


Found 2 errors in the same file, starting at: src/components/messages/FlowDiagram/useLayout.ts:8
```

So once you fix the Graphlib, that should be it 🤞

**Comment by johnsimons** [comment]
Actually, just read the error better, it seems the latest [change](https://github.com/dagrejs/dagre/commit/ec51f60d5d224fbbbc95689e4388f0620f7b94e8) broke it more than before, sorry.

**Comment by johnsimons** [comment]
You may need to add more [JSDoc tags to the code](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) so that the generation of the `d.ts` file includes all the public APIs.

**Comment by rustedgrail** [comment]
I think that was because I changed to exporting a type instead of a class, when the real issue was just the name was being shadowed. I expect (and saw in a simple example) that there should be an error, but I think the .d.ts file doesn't go through as much checking as a .ts file does.

**Comment by MarcSustainableShift** [comment]
> Yep, we're also seeing the same `Type 'typeof Graph' has no construct signatures.` when doing `new graphlib.Graph()` in [alveusgg/alveusgg#1664](https://github.com/alveusgg/alveusgg/pull/1664)

Same issue here

**Comment by wlc534** [comment]
<img width="1468" height="502" alt="Image" src="https://github.com/user-attachments/assets/5b642e73-2b99-4dc4-aaf1-e72210db9881" />   "@dagrejs/dagre": "^2.0.1",  me too

**Comment by rustedgrail** [comment]
I've updated master with another version of exporting graph. Please let me know if that helps.

**Comment by jomonty** [comment]
Having the same issue using vite: `Dynamic require of "@dagrejs/graphlib" is not supported`

As an aside - also having an issue with eslint. 

It seems that as we are now using the imported `Graph` class from graphlib, the function signature `node(id: string | Label): Node<T>` defined [here](https://github.com/dagrejs/dagre/commit/75e2e474b894b5b494c23e5f885b2575e6c5b73b#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8L35) has been replaced with `node(name: string) : any` as defined by version 2.2.4 of graphlib and imported by dagrejs. We have quite strict eslint rules and would prefer not to have an `any` return type here. That said we are unable to run with dagre 2.0.3 due to the vite issue above!

I can see in newer versions of graphlib this has been updated to `node(name: string): NodeLabel` - do you have an expectation for when you'll bump the version of graphlib used by dagrejs?

**Comment by fastlorenzo** [comment]
FYI after a lot of trial and error (and bit of AI help), I managed to get it work with vite.

1. Use the following vite plugin:

```javascript
import fs from 'fs';
import type { Plugin, UserConfig } from 'vite';

/**
 * Vite plugin to fix @dagrejs/dagre's dynamic require of @dagrejs/graphlib.
 *
 * Uses esbuild's onLoad hook during pre-bundling to inject the graphlib import
 * and replace dynamic require calls before the code is bundled.
 *
 * See: https://github.com/dagrejs/dagre/issues/492
 */
export default function dagreGraphlibPlugin(): Plugin {
    return {
        name: 'dagre-graphlib-fix',
        config(): Omit<UserConfig, 'plugins'> {
            return {
                optimizeDeps: {
                    esbuildOptions: {
                        plugins: [
                            {
                                name: 'dagre-graphlib-esbuild',
                                setup(build) {
                                    // Intercept the dagre ESM file during pre-bundling
                                    build.onLoad({ filter: /dagre\.esm\.js$/ }, async (args) => {
                                        let contents = await fs.promises.readFile(args.path, 'utf8');

                                        // Add graphlib import at the top
                                        const graphlibImport = `import * as __graphlib__ from '@dagrejs/graphlib';\n`;
                                        contents = graphlibImport + contents;

                                        // Replace all dynamic require patterns
                                        contents = contents.replace(
                                            /g\(\s*["']@dagrejs\/graphlib["']\s*\)/g,
                                            '__graphlib__'
                                        );

                                        return {
                                            contents,
                                            loader: 'js' as const,
                                        };
                                    });
                                },
                            },
                        ],
                    },
                },
            };
        },
    };
}
```

2. Update `vite.config.js` to use it:

```javascript
{
    plugins: [
        dagreGraphlibPlugin(),
   ],
    optimizeDeps: {
        include: ['@dagrejs/dagre', '@dagrejs/graphlib'],
    },
}
```

Quick and dirty fix, but does the job until a new version which fixes this bug is released.
